# Base configs
baseurl: "https://svakula.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Shrijith Vakula"
subtitle: "Stuff I Found 'Cool' In The Moment"
author: "Shrijith Vakula"
header:
 title: "Photography"
 subtitle: "by Shrijith Vakula"
footer:
 name: "I'm Shrijith Vakula"
 bio: "Aspiring amateur photographer."
 github: "https://github.com/svakula"
web_design: ""
social_urls:
  facebook: ""
  twitter: "https://www.twitter.com/svakulax"
  instagram: "https://www.instagram.com/spleenjith"
  dribbble: ""
  linkedin: "https://www.linkedin.com/in/shrijith-vakula-178649194/"
  github: "https://www.github.com/svakula"
